#!/bin/bash

files=`find . -type f -name "*.go" ! -path "vendor/*" |xargs`
for file in $files; do
    gofmt -w=true ${file}
done

rm -f ./bin/lesscms

go build -race -o ./bin/lesscms ./main.go

./bin/lesscms -logtostderr=true 

