#!/bin/bash

# export GOPATH=$GOPATH:/opt/gopath/src/code.hooto.com/hooto/alphapress/vendor

rm -f ./bin/hooto-alphapress

#go build -race -o ./bin/hooto-alphapress ./main.go
go build -o ./bin/hooto-alphapress ./main.go

./bin/hooto-alphapress -logtostderr=true 

